name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HF: ${{ secrets.MLOP_PROJECT }}
        run: git remote add space https://FaizanArif:$HF@huggingface.co/spaces/FaizanArif/MLOPs_Project
      - name: Push to hub
        env:
          HF: ${{ secrets.MLOP_PROJECT }}
        run: git push --force https://FaizanArif:$HF@huggingface.co/spaces/FaizanArif/MLOPs_Project main
